after_success:
  - npm run coveralls

before_script:
  - npm i -g eslint
  - eslint .

dist: trusty

language: node_js

node_js:
  - 8
  - 10
  - 10.1.0

notifications:
  slack:
    rooms:
      - secure: "SOyb1L7KTf/NxLj+lunFnq4UJxXVIHHwFdPwIe4c3VbBZOeUR/0x+b2swNgJ+/rnra0Th+RCZTZ99LrBGpFchFI6hYXjLVdGGL8LhyfUuREG2tW7/MsQfTQuZwqqc6cc0trn4VGSJYVHDW428XUPc3VIJyrV1KP8NBsmMl499AY="
    on_success: always

sudo: false
